In [12]:
import numpy as np
from pandas import Series, DataFrame     #「Series」と「DataFrame」はそのまま使うことが多いので、個別にロード。
import pandas as pd

In [43]:
# NFLのデータをサンプルとして使います。
import webbrowser
website = 'http://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(website)

True

In [49]:
# 「pd.read_clipboard」で、コピーしているデータフレームを読み込む。
#  今回は、clipboardだとバグるので、csvで保存してから読み込む。
# pandasには「read_txt」はない。エクセルでcsvにしてから「read_csv」を使うしかない。
nfl_frame = pd.read_csv("NFLwiki.csv",sep=",")

In [50]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Dallas Cowboys,502,374,6,0.573,1960,882,NFC East
1,2,Green Bay Packers,737,562,37,0.565,1921,"1,336",NFC North
2,3,Chicago Bears,749,579,42,0.562,1920,"1,370",NFC North
3,4,Miami Dolphins,445,351,4,0.559,1966,800,AFC East
4,5,New England Patriots[b],489,386,9,0.558,1960,884,AFC East
5,6,Minnesota Vikings,470,390,10,0.546,1961,870,NFC North
6,7,Baltimore Ravens,190,161,1,0.541,1996,352,AFC North
7,8,New York Giants,687,585,33,0.539,1925,"1,305",NFC East
8,9,Denver Broncos,470,404,10,0.537,1960,884,AFC West
9,10,San Francisco 49ers,528,460,14,0.534,1950,"1,002",NFC West
10,11,Pittsburgh Steelers,614,538,20,0.532,1933,"1,172",AFC North
11,12,Oakland Raiders,462,411,11,0.529,1960,884,AFC West
12,13,Indianapolis Colts[c],506,453,7,0.527,1953,966,AFC South
13,14,Kansas City Chiefs,457,415,12,0.524,1960,884,AFC West
14,15,Seattle Seahawks,334,325,1,0.507,1976,660,NFC West
15,16,Washington Redskins,595,581,28,0.506,1932,"1,202",NFC East
16,17,Carolina Panthers,183,184,1,0.499,1995,368,NFC South
17,18,Los Angeles Chargers,435,438,11,0.498,1960,884,AFC West
18,19,Los Angeles Rams,555,559,21,0.498,1937,"1,135",NFC West
19,20,Cleveland Browns,462,482,10,0.490,1950,954,AFC North
20,21,Philadelphia Eagles,568,594,26,0.489,1933,"1,188",NFC East
21,22,Tennessee Titans,422,456,6,0.481,1960,884,AFC South
22,23,Buffalo Bills,409,467,8,0.467,1960,884,AFC East
23,24,Detroit Lions,553,648,32,0.461,1930,"1,233",NFC North
24,25,Cincinnati Bengals,351,417,4,0.457,1968,772,AFC North
25,26,New York Jets,397,479,8,0.454,1960,884,AFC East
26,27,Jacksonville Jaguars,165,203,0,0.448,1995,368,AFC South
27,28,New Orleans Saints,349,432,5,0.447,1967,786,NFC South
28,29,Atlanta Falcons,351,443,6,0.443,1966,790,NFC South
29,30,Houston Texans,110,146,0,0.430,2002,256,AFC South
30,31,Arizona Cardinals,550,740,40,0.429,1920,"1,330",NFC West
31,32,Tampa Bay Buccaneers,255,404,1,0.387,1976,660,NFC South

In [53]:
# 「.columns」で列名を出力。
nfl_frame.columns

Index(['Rank', 'Team', 'Won', 'Lost', 'Tied', 'Pct.', 'First NFL Season',
       'Total Games', 'Division'],
      dtype='object')

In [55]:
nfl_frame['First NFL Season']

0     1960
1     1921
2     1920
3     1966
4     1960
5     1961
6     1996
7     1925
8     1960
9     1950
10    1933
11    1960
12    1953
13    1960
14    1976
15    1932
16    1995
17    1960
18    1937
19    1950
20    1933
21    1960
22    1960
23    1930
24    1968
25    1960
26    1995
27    1967
28    1966
29    2002
30    1920
31    1976
Name: First NFL Season, dtype: int64

In [56]:
# オブジェクトの属性のような書き方も可能
nfl_frame.Team

0              Dallas Cowboys
1           Green Bay Packers
2               Chicago Bears
3              Miami Dolphins
4     New England Patriots[b]
5           Minnesota Vikings
6            Baltimore Ravens
7             New York Giants
8              Denver Broncos
9         San Francisco 49ers
10        Pittsburgh Steelers
11            Oakland Raiders
12      Indianapolis Colts[c]
13         Kansas City Chiefs
14           Seattle Seahawks
15        Washington Redskins
16          Carolina Panthers
17       Los Angeles Chargers
18           Los Angeles Rams
19           Cleveland Browns
20        Philadelphia Eagles
21           Tennessee Titans
22              Buffalo Bills
23              Detroit Lions
24         Cincinnati Bengals
25              New York Jets
26       Jacksonville Jaguars
27         New Orleans Saints
28            Atlanta Falcons
29             Houston Texans
30          Arizona Cardinals
31       Tampa Bay Buccaneers
Name: Team, dtype: object

In [57]:
# 特定のカラムで新しいDataFrameを作る
DataFrame(nfl_frame,columns=['Team','First Season','Total Games'])

                       Team  First Season Total Games
0            Dallas Cowboys           NaN         882
1         Green Bay Packers           NaN       1,336
2             Chicago Bears           NaN       1,370
3            Miami Dolphins           NaN         800
4   New England Patriots[b]           NaN         884
5         Minnesota Vikings           NaN         870
6          Baltimore Ravens           NaN         352
7           New York Giants           NaN       1,305
8            Denver Broncos           NaN         884
9       San Francisco 49ers           NaN       1,002
10      Pittsburgh Steelers           NaN       1,172
11          Oakland Raiders           NaN         884
12    Indianapolis Colts[c]           NaN         966
13       Kansas City Chiefs           NaN         884
14         Seattle Seahawks           NaN         660
15      Washington Redskins           NaN       1,202
16        Carolina Panthers           NaN         368
17     Los Angeles Chargers           NaN         884
18         Los Angeles Rams           NaN       1,135
19         Cleveland Browns           NaN         954
20      Philadelphia Eagles           NaN       1,188
21         Tennessee Titans           NaN         884
22            Buffalo Bills           NaN         884
23            Detroit Lions           NaN       1,233
24       Cincinnati Bengals           NaN         772
25            New York Jets           NaN         884
26     Jacksonville Jaguars           NaN         368
27       New Orleans Saints           NaN         786
28          Atlanta Falcons           NaN         790
29           Houston Texans           NaN         256
30        Arizona Cardinals           NaN       1,330
31     Tampa Bay Buccaneers           NaN         660

In [58]:
DataFrame(nfl_frame,columns=['Team','First Season','Total Games','Stadium'])

                       Team  First Season Total Games  Stadium
0            Dallas Cowboys           NaN         882      NaN
1         Green Bay Packers           NaN       1,336      NaN
2             Chicago Bears           NaN       1,370      NaN
3            Miami Dolphins           NaN         800      NaN
4   New England Patriots[b]           NaN         884      NaN
5         Minnesota Vikings           NaN         870      NaN
6          Baltimore Ravens           NaN         352      NaN
7           New York Giants           NaN       1,305      NaN
8            Denver Broncos           NaN         884      NaN
9       San Francisco 49ers           NaN       1,002      NaN
10      Pittsburgh Steelers           NaN       1,172      NaN
11          Oakland Raiders           NaN         884      NaN
12    Indianapolis Colts[c]           NaN         966      NaN
13       Kansas City Chiefs           NaN         884      NaN
14         Seattle Seahawks           NaN         660      NaN
15      Washington Redskins           NaN       1,202      NaN
16        Carolina Panthers           NaN         368      NaN
17     Los Angeles Chargers           NaN         884      NaN
18         Los Angeles Rams           NaN       1,135      NaN
19         Cleveland Browns           NaN         954      NaN
20      Philadelphia Eagles           NaN       1,188      NaN
21         Tennessee Titans           NaN         884      NaN
22            Buffalo Bills           NaN         884      NaN
23            Detroit Lions           NaN       1,233      NaN
24       Cincinnati Bengals           NaN         772      NaN
25            New York Jets           NaN         884      NaN
26     Jacksonville Jaguars           NaN         368      NaN
27       New Orleans Saints           NaN         786      NaN
28          Atlanta Falcons           NaN         790      NaN
29           Houston Texans           NaN         256      NaN
30        Arizona Cardinals           NaN       1,330      NaN
31     Tampa Bay Buccaneers           NaN         660      NaN

In [59]:
# 先頭だけを表示
nfl_frame.head()

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Dallas Cowboys,502,374,6,0.573,1960,882,NFC East
1,2,Green Bay Packers,737,562,37,0.565,1921,"1,336",NFC North
2,3,Chicago Bears,749,579,42,0.562,1920,"1,370",NFC North
3,4,Miami Dolphins,445,351,4,0.559,1966,800,AFC East
4,5,New England Patriots[b],489,386,9,0.558,1960,884,AFC East

In [60]:
#最後だけを表示
nfl_frame.tail()

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
27,28,New Orleans Saints,349,432,5,0.447,1967,786,NFC South
28,29,Atlanta Falcons,351,443,6,0.443,1966,790,NFC South
29,30,Houston Texans,110,146,0,0.430,2002,256,AFC South
30,31,Arizona Cardinals,550,740,40,0.429,1920,"1,330",NFC West
31,32,Tampa Bay Buccaneers,255,404,1,0.387,1976,660,NFC South

In [61]:
# indexを使って、行を取り出せる
nfl_frame.ix[3]

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

Rank                             4
Team                Miami Dolphins
Won                            445
Lost                           351
Tied                             4
Pct.                         0.559
First NFL Season              1966
Total Games                    800
Division                  AFC East
Name: 3, dtype: object

In [62]:
# 列全体に値を代入
nfl_frame['Stadium']="Levi's Stadium" #文字列内に「'」があるので、全体は「”」で囲む

In [63]:
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,502,374,6,0.573,1960,882,NFC East,Levi's Stadium
1,2,Green Bay Packers,737,562,37,0.565,1921,"1,336",NFC North,Levi's Stadium
2,3,Chicago Bears,749,579,42,0.562,1920,"1,370",NFC North,Levi's Stadium
3,4,Miami Dolphins,445,351,4,0.559,1966,800,AFC East,Levi's Stadium
4,5,New England Patriots[b],489,386,9,0.558,1960,884,AFC East,Levi's Stadium
5,6,Minnesota Vikings,470,390,10,0.546,1961,870,NFC North,Levi's Stadium
6,7,Baltimore Ravens,190,161,1,0.541,1996,352,AFC North,Levi's Stadium
7,8,New York Giants,687,585,33,0.539,1925,"1,305",NFC East,Levi's Stadium
8,9,Denver Broncos,470,404,10,0.537,1960,884,AFC West,Levi's Stadium
9,10,San Francisco 49ers,528,460,14,0.534,1950,"1,002",NFC West,Levi's Stadium
10,11,Pittsburgh Steelers,614,538,20,0.532,1933,"1,172",AFC North,Levi's Stadium
11,12,Oakland Raiders,462,411,11,0.529,1960,884,AFC West,Levi's Stadium
12,13,Indianapolis Colts[c],506,453,7,0.527,1953,966,AFC South,Levi's Stadium
13,14,Kansas City Chiefs,457,415,12,0.524,1960,884,AFC West,Levi's Stadium
14,15,Seattle Seahawks,334,325,1,0.507,1976,660,NFC West,Levi's Stadium
15,16,Washington Redskins,595,581,28,0.506,1932,"1,202",NFC East,Levi's Stadium
16,17,Carolina Panthers,183,184,1,0.499,1995,368,NFC South,Levi's Stadium
17,18,Los Angeles Chargers,435,438,11,0.498,1960,884,AFC West,Levi's Stadium
18,19,Los Angeles Rams,555,559,21,0.498,1937,"1,135",NFC West,Levi's Stadium
19,20,Cleveland Browns,462,482,10,0.490,1950,954,AFC North,Levi's Stadium
20,21,Philadelphia Eagles,568,594,26,0.489,1933,"1,188",NFC East,Levi's Stadium
21,22,Tennessee Titans,422,456,6,0.481,1960,884,AFC South,Levi's Stadium
22,23,Buffalo Bills,409,467,8,0.467,1960,884,AFC East,Levi's Stadium
23,24,Detroit Lions,553,648,32,0.461,1930,"1,233",NFC North,Levi's Stadium
24,25,Cincinnati Bengals,351,417,4,0.457,1968,772,AFC North,Levi's Stadium
25,26,New York Jets,397,479,8,0.454,1960,884,AFC East,Levi's Stadium
26,27,Jacksonville Jaguars,165,203,0,0.448,1995,368,AFC South,Levi's Stadium
27,28,New Orleans Saints,349,432,5,0.447,1967,786,NFC South,Levi's Stadium
28,29,Atlanta Falcons,351,443,6,0.443,1966,790,NFC South,Levi's Stadium
29,30,Houston Texans,110,146,0,0.430,2002,256,AFC South,Levi's Stadium
30,31,Arizona Cardinals,550,740,40,0.429,1920,"1,330",NFC West,Levi's Stadium
31,32,Tampa Bay Buccaneers,255,404,1,0.387,1976,660,NFC South,Levi's Stadium

In [67]:
# 長さが合っていれば、列への代入が可能。
nfl_frame["Stadium"] = np.arange(32)
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,502,374,6,0.573,1960,882,NFC East,0
1,2,Green Bay Packers,737,562,37,0.565,1921,"1,336",NFC North,1
2,3,Chicago Bears,749,579,42,0.562,1920,"1,370",NFC North,2
3,4,Miami Dolphins,445,351,4,0.559,1966,800,AFC East,3
4,5,New England Patriots[b],489,386,9,0.558,1960,884,AFC East,4
5,6,Minnesota Vikings,470,390,10,0.546,1961,870,NFC North,5
6,7,Baltimore Ravens,190,161,1,0.541,1996,352,AFC North,6
7,8,New York Giants,687,585,33,0.539,1925,"1,305",NFC East,7
8,9,Denver Broncos,470,404,10,0.537,1960,884,AFC West,8
9,10,San Francisco 49ers,528,460,14,0.534,1950,"1,002",NFC West,9
10,11,Pittsburgh Steelers,614,538,20,0.532,1933,"1,172",AFC North,10
11,12,Oakland Raiders,462,411,11,0.529,1960,884,AFC West,11
12,13,Indianapolis Colts[c],506,453,7,0.527,1953,966,AFC South,12
13,14,Kansas City Chiefs,457,415,12,0.524,1960,884,AFC West,13
14,15,Seattle Seahawks,334,325,1,0.507,1976,660,NFC West,14
15,16,Washington Redskins,595,581,28,0.506,1932,"1,202",NFC East,15
16,17,Carolina Panthers,183,184,1,0.499,1995,368,NFC South,16
17,18,Los Angeles Chargers,435,438,11,0.498,1960,884,AFC West,17
18,19,Los Angeles Rams,555,559,21,0.498,1937,"1,135",NFC West,18
19,20,Cleveland Browns,462,482,10,0.490,1950,954,AFC North,19
20,21,Philadelphia Eagles,568,594,26,0.489,1933,"1,188",NFC East,20
21,22,Tennessee Titans,422,456,6,0.481,1960,884,AFC South,21
22,23,Buffalo Bills,409,467,8,0.467,1960,884,AFC East,22
23,24,Detroit Lions,553,648,32,0.461,1930,"1,233",NFC North,23
24,25,Cincinnati Bengals,351,417,4,0.457,1968,772,AFC North,24
25,26,New York Jets,397,479,8,0.454,1960,884,AFC East,25
26,27,Jacksonville Jaguars,165,203,0,0.448,1995,368,AFC South,26
27,28,New Orleans Saints,349,432,5,0.447,1967,786,NFC South,27
28,29,Atlanta Falcons,351,443,6,0.443,1966,790,NFC South,28
29,30,Houston Texans,110,146,0,0.430,2002,256,AFC South,29
30,31,Arizona Cardinals,550,740,40,0.429,1920,"1,330",NFC West,30
31,32,Tampa Bay Buccaneers,255,404,1,0.387,1976,660,NFC South,31

In [68]:
# SeriesをDataFrameに追加する
stadiums = Series(["Levi's Stadium","AT&T Stadium"],index=[4,0])

In [69]:
stadiums

4    Levi's Stadium
0      AT&T Stadium
dtype: object

In [70]:
nfl_frame['Stadium']=stadiums
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division,Stadium
0,1,Dallas Cowboys,502,374,6,0.573,1960,882,NFC East,AT&T Stadium
1,2,Green Bay Packers,737,562,37,0.565,1921,"1,336",NFC North,NaN
2,3,Chicago Bears,749,579,42,0.562,1920,"1,370",NFC North,NaN
3,4,Miami Dolphins,445,351,4,0.559,1966,800,AFC East,NaN
4,5,New England Patriots[b],489,386,9,0.558,1960,884,AFC East,Levi's Stadium
5,6,Minnesota Vikings,470,390,10,0.546,1961,870,NFC North,NaN
6,7,Baltimore Ravens,190,161,1,0.541,1996,352,AFC North,NaN
7,8,New York Giants,687,585,33,0.539,1925,"1,305",NFC East,NaN
8,9,Denver Broncos,470,404,10,0.537,1960,884,AFC West,NaN
9,10,San Francisco 49ers,528,460,14,0.534,1950,"1,002",NFC West,NaN
10,11,Pittsburgh Steelers,614,538,20,0.532,1933,"1,172",AFC North,NaN
11,12,Oakland Raiders,462,411,11,0.529,1960,884,AFC West,NaN
12,13,Indianapolis Colts[c],506,453,7,0.527,1953,966,AFC South,NaN
13,14,Kansas City Chiefs,457,415,12,0.524,1960,884,AFC West,NaN
14,15,Seattle Seahawks,334,325,1,0.507,1976,660,NFC West,NaN
15,16,Washington Redskins,595,581,28,0.506,1932,"1,202",NFC East,NaN
16,17,Carolina Panthers,183,184,1,0.499,1995,368,NFC South,NaN
17,18,Los Angeles Chargers,435,438,11,0.498,1960,884,AFC West,NaN
18,19,Los Angeles Rams,555,559,21,0.498,1937,"1,135",NFC West,NaN
19,20,Cleveland Browns,462,482,10,0.490,1950,954,AFC North,NaN
20,21,Philadelphia Eagles,568,594,26,0.489,1933,"1,188",NFC East,NaN
21,22,Tennessee Titans,422,456,6,0.481,1960,884,AFC South,NaN
22,23,Buffalo Bills,409,467,8,0.467,1960,884,AFC East,NaN
23,24,Detroit Lions,553,648,32,0.461,1930,"1,233",NFC North,NaN
24,25,Cincinnati Bengals,351,417,4,0.457,1968,772,AFC North,NaN
25,26,New York Jets,397,479,8,0.454,1960,884,AFC East,NaN
26,27,Jacksonville Jaguars,165,203,0,0.448,1995,368,AFC South,NaN
27,28,New Orleans Saints,349,432,5,0.447,1967,786,NFC South,NaN
28,29,Atlanta Falcons,351,443,6,0.443,1966,790,NFC South,NaN
29,30,Houston Texans,110,146,0,0.430,2002,256,AFC South,NaN
30,31,Arizona Cardinals,550,740,40,0.429,1920,"1,330",NFC West,NaN
31,32,Tampa Bay Buccaneers,255,404,1,0.387,1976,660,NFC South,NaN

In [71]:
# 列を消すことも可能
del nfl_frame['Stadium']
nfl_frame

,Rank,Team,Won,Lost,Tied,Pct.,First NFL Season,Total Games,Division
0,1,Dallas Cowboys,502,374,6,0.573,1960,882,NFC East
1,2,Green Bay Packers,737,562,37,0.565,1921,"1,336",NFC North
2,3,Chicago Bears,749,579,42,0.562,1920,"1,370",NFC North
3,4,Miami Dolphins,445,351,4,0.559,1966,800,AFC East
4,5,New England Patriots[b],489,386,9,0.558,1960,884,AFC East
5,6,Minnesota Vikings,470,390,10,0.546,1961,870,NFC North
6,7,Baltimore Ravens,190,161,1,0.541,1996,352,AFC North
7,8,New York Giants,687,585,33,0.539,1925,"1,305",NFC East
8,9,Denver Broncos,470,404,10,0.537,1960,884,AFC West
9,10,San Francisco 49ers,528,460,14,0.534,1950,"1,002",NFC West
10,11,Pittsburgh Steelers,614,538,20,0.532,1933,"1,172",AFC North
11,12,Oakland Raiders,462,411,11,0.529,1960,884,AFC West
12,13,Indianapolis Colts[c],506,453,7,0.527,1953,966,AFC South
13,14,Kansas City Chiefs,457,415,12,0.524,1960,884,AFC West
14,15,Seattle Seahawks,334,325,1,0.507,1976,660,NFC West
15,16,Washington Redskins,595,581,28,0.506,1932,"1,202",NFC East
16,17,Carolina Panthers,183,184,1,0.499,1995,368,NFC South
17,18,Los Angeles Chargers,435,438,11,0.498,1960,884,AFC West
18,19,Los Angeles Rams,555,559,21,0.498,1937,"1,135",NFC West
19,20,Cleveland Browns,462,482,10,0.490,1950,954,AFC North
20,21,Philadelphia Eagles,568,594,26,0.489,1933,"1,188",NFC East
21,22,Tennessee Titans,422,456,6,0.481,1960,884,AFC South
22,23,Buffalo Bills,409,467,8,0.467,1960,884,AFC East
23,24,Detroit Lions,553,648,32,0.461,1930,"1,233",NFC North
24,25,Cincinnati Bengals,351,417,4,0.457,1968,772,AFC North
25,26,New York Jets,397,479,8,0.454,1960,884,AFC East
26,27,Jacksonville Jaguars,165,203,0,0.448,1995,368,AFC South
27,28,New Orleans Saints,349,432,5,0.447,1967,786,NFC South
28,29,Atlanta Falcons,351,443,6,0.443,1966,790,NFC South
29,30,Houston Texans,110,146,0,0.430,2002,256,AFC South
30,31,Arizona Cardinals,550,740,40,0.429,1920,"1,330",NFC West
31,32,Tampa Bay Buccaneers,255,404,1,0.387,1976,660,NFC South

In [72]:
# 辞書からDataFramesを作ることもできます。
data = {'City':['SF','LA','NYC'],
        'Population':[837000,3880000,8400000]}

city_frame = DataFrame(data)

#Show
city_frame

  City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000

In [73]:
# pandas.DataFrameの機能の全体は、Webで確認できます。
website = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.html'
webbrowser.open(website)

True